# Generated by Django 2.0.7 on 2018-12-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_timesheet_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='hours',
            field=models.FloatField(default=0),
        ),
    ]
